version: '3.7'
services:
  zookeeper:
    image: zookeeper:3.9.0
    hostname: zookeeper
    container_name: zookeeper-datetime
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks: 
      - datetime
  kafka:
    image: wurstmeister/kafka:latest
    restart: unless-stopped
    container_name: "kafka-datetime"
    ports:
      - "9092:9092"
    expose:
      - "9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-datetime:2181/kafka
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: kafka-datetime
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-datetime:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
    networks: 
      - datetime      
  pinot-controller:
    image: apachepinot/pinot:1.0.0
    command: "StartController -zkAddress zookeeper-datetime:2181"
    container_name: "pinot-controller-datetime"
    volumes:
      - ./config:/config
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      - zookeeper
    networks: 
      - datetime
  pinot-broker:
    image: apachepinot/pinot:1.0.0
    command: "StartBroker -zkAddress zookeeper-datetime:2181"
    restart: unless-stopped
    container_name: "pinot-broker-datetime"
    ports:
      - "8099:8099"
    depends_on:
      - pinot-controller
    networks: 
      - datetime
  pinot-server:
    image: apachepinot/pinot:1.0.0
    command: "StartServer -zkAddress zookeeper-datetime:2181"
    restart: unless-stopped
    container_name: "pinot-server-datetime"
    depends_on:
      - pinot-broker
    networks: 
      - datetime
networks:
  datetime:
    name: datetime