version: "3"
services:
  zookeeper:
    image: zookeeper:3.8.0
    hostname: zookeeper
    container_name: zookeeper-querysegment
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks: 
      - querysegment
  kafka:
    image: wurstmeister/kafka:latest
    restart: unless-stopped
    container_name: "kafka-querysegment"
    ports:
      - "9092:9092"
    expose:
      - "9093"
    depends_on:
     - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-querysegment:2181/kafka
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: kafka-querysegment
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-querysegment:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
    networks: 
      - querysegment
  pinot-controller:
    image: apachepinot/pinot:1.0.0
    command: "StartController -zkAddress zookeeper-querysegment:2181"
    container_name: "pinot-controller-querysegment"
    restart: unless-stopped
    ports:
      - "9000:9000"
    networks: 
      - querysegment
  pinot-broker:
    image: apachepinot/pinot:1.0.0
    command: "StartBroker -zkAddress zookeeper-querysegment:2181"
    container_name: "pinot-broker-querysegment"
    restart: unless-stopped
    ports:
      - "8099:8099"
    networks: 
      - querysegment
  pinot-server:
    image: apachepinot/pinot:1.0.0
    command: "StartServer -zkAddress zookeeper-querysegment:2181"
    container_name: "pinot-server-querysegment"
    ports:
      - "5006:5005"
    expose:
      - "8097"
    restart: unless-stopped
    networks: 
      - querysegment
networks:
  querysegment:
    name: querysegment
