version: '3.7'
services:
  zookeeper:
    image: zookeeper:3.9.0
    hostname: zookeeper
    container_name: zookeeper-nypd
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks: 
      - nypd
  pinot-controller:
    image: apachepinot/pinot:1.0.0-11-ms-openjdk
    command: "StartController -zkAddress zookeeper-nypd:2181"
    container_name: "pinot-controller-nypd"
    volumes:
      - ./config:/config
      - ./data:/data
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      - zookeeper
    networks: 
      - nypd
  pinot-broker:
    image: apachepinot/pinot:1.0.0-11-ms-openjdk
    command: "StartBroker -zkAddress zookeeper-nypd:2181"
    restart: unless-stopped
    container_name: "pinot-broker-nypd"
    ports:
      - "8099:8099"
    depends_on:
      - pinot-controller
    networks: 
      - nypd
  pinot-server:
    image: apachepinot/pinot:1.0.0-11-ms-openjdk
    command: "StartServer -zkAddress zookeeper-nypd:2181"
    restart: unless-stopped
    container_name: "pinot-server-nypd"
    depends_on:
      - pinot-broker
    networks: 
      - nypd
  pinot-minion:
    image: apachepinot/pinot:1.0.0-11-ms-openjdk
    command: "StartMinion -zkAddress zookeeper-nypd:2181"
    restart: unless-stopped
    container_name: "pinot-minion-nypd"
    volumes:
      - ./data:/data
    depends_on:
      - pinot-broker
    networks: 
      - nypd
networks:
  nypd:
    name: nypd