version: '3.7'
services:
  zookeeper:
    image: zookeeper:3.9.0
    hostname: zookeeper
    container_name: zookeeper-groovy
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks: 
      - groovy
  pinot-controller:
    image: apachepinot/pinot:1.0.0
    command: "StartController -zkAddress zookeeper-groovy:2181 -config /config/controller-conf.conf"
    container_name: "pinot-controller-groovy"
    volumes:
      - ./config:/config
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "5005:5005"
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
      - zookeeper
    networks: 
      - groovy
  pinot-broker:
    image: apachepinot/pinot:1.0.0
    command: "StartBroker -zkAddress zookeeper-groovy:2181"
    restart: unless-stopped
    container_name: "pinot-broker-groovy"
    ports:
      - "8099:8099"
    depends_on:
      - pinot-controller
    networks: 
      - groovy
  pinot-server:
    image: apachepinot/pinot:1.0.0
    command: "StartServer -zkAddress zookeeper-groovy:2181"
    restart: unless-stopped
    container_name: "pinot-server-groovy"
    depends_on:
      - pinot-broker
    networks: 
      - groovy
  kafka:
    image: wurstmeister/kafka:latest
    restart: unless-stopped
    container_name: "kafka-groovy"
    ports:
      - "9092:9092"
    expose:
      - "9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-groovy:2181/kafka
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: kafka-groovy
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-groovy:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
    networks: 
      - groovy

networks:
  groovy:
    name: groovy